-- Device / non-pharma products module.
-- Safe rollout: creates separate tables and RPCs; it does not change pharmacy tables.

create extension if not exists pgcrypto;

create table if not exists public.device_products (
  id uuid primary key default gen_random_uuid(),
  external_code integer not null unique,
  name text not null,
  secondary_name text,
  category text,
  brand_code integer,
  brand_name text,
  model text,
  presentation_name text,
  sale_price numeric(14,4),
  default_cost numeric(14,4),
  active boolean not null default true,
  requires_serial boolean not null default true,
  requires_expiration boolean not null default false,
  source_file text,
  source_loaded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_device_products_active on public.device_products(active);
create index if not exists idx_device_products_name on public.device_products using gin(to_tsvector('spanish', coalesce(name,'') || ' ' || coalesce(secondary_name,'') || ' ' || coalesce(brand_name,'') || ' ' || coalesce(model,'')));

drop trigger if exists trg_device_products_updated_at on public.device_products;
create trigger trg_device_products_updated_at
before update on public.device_products
for each row execute function public.pharma_touch_updated_at();

create table if not exists public.device_units (
  id uuid primary key default gen_random_uuid(),
  device_product_id uuid not null references public.device_products(id),
  serial_code text not null,
  normalized_serial text generated always as (lower(regexp_replace(trim(serial_code), '\s+', '', 'g'))) stored,
  lot_no text,
  expires_at date,
  status text not null default 'available',
  cost numeric(14,4),
  source_doc_no text,
  source_file text,
  registered_by uuid references public.app_users(id),
  registered_at timestamptz not null default now(),
  sold_at timestamptz,
  sold_by uuid references public.app_users(id),
  sale_id uuid,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint device_units_status_check check (status in ('available','sold','inactive','damaged','lost','retired')),
  constraint device_units_serial_not_blank check (length(trim(serial_code)) > 0)
);

create unique index if not exists ux_device_units_normalized_serial on public.device_units(normalized_serial);
create index if not exists idx_device_units_product_status on public.device_units(device_product_id, status);
create index if not exists idx_device_units_expires on public.device_units(expires_at);

drop trigger if exists trg_device_units_updated_at on public.device_units;
create trigger trg_device_units_updated_at
before update on public.device_units
for each row execute function public.pharma_touch_updated_at();

create table if not exists public.device_sales (
  id uuid primary key default gen_random_uuid(),
  sale_no bigint generated by default as identity unique,
  expediente text not null,
  status text not null default 'confirmed',
  created_by uuid references public.app_users(id),
  confirmed_at timestamptz not null default now(),
  note text,
  created_at timestamptz not null default now(),
  constraint device_sales_status_check check (status in ('confirmed','voided'))
);

create index if not exists idx_device_sales_expediente on public.device_sales(expediente);
create index if not exists idx_device_sales_confirmed_at on public.device_sales(confirmed_at);

create table if not exists public.device_sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.device_sales(id) on delete cascade,
  device_unit_id uuid not null references public.device_units(id),
  device_product_id uuid not null references public.device_products(id),
  serial_code text not null,
  product_name_snapshot text not null,
  price numeric(14,4),
  cost numeric(14,4),
  created_at timestamptz not null default now(),
  unique (sale_id, device_unit_id)
);

create index if not exists idx_device_sale_items_product on public.device_sale_items(device_product_id);
create index if not exists idx_device_sale_items_serial on public.device_sale_items(serial_code);
create unique index if not exists ux_device_sale_items_unit on public.device_sale_items(device_unit_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'device_units_sale_id_fkey'
      and conrelid = 'public.device_units'::regclass
  ) then
    alter table public.device_units
      add constraint device_units_sale_id_fkey
      foreign key (sale_id) references public.device_sales(id);
  end if;
end;
$$;

create table if not exists public.device_inventory_movements (
  id uuid primary key default gen_random_uuid(),
  device_unit_id uuid references public.device_units(id),
  device_product_id uuid not null references public.device_products(id),
  serial_code text,
  movement_type text not null,
  qty_delta integer not null,
  source_type text,
  source_id uuid,
  source_event_key text,
  note text,
  created_by uuid references public.app_users(id),
  created_at timestamptz not null default now(),
  constraint device_inventory_movements_qty_check check (qty_delta <> 0),
  constraint device_inventory_movements_type_check check (movement_type in ('receive','sale','sale_void','admin_adjustment'))
);

create unique index if not exists ux_device_inventory_movements_source_event_key
on public.device_inventory_movements(source_event_key)
where source_event_key is not null;

create index if not exists idx_device_inventory_movements_product_created
on public.device_inventory_movements(device_product_id, created_at);

alter table public.device_products enable row level security;
alter table public.device_units enable row level security;
alter table public.device_sales enable row level security;
alter table public.device_sale_items enable row level security;
alter table public.device_inventory_movements enable row level security;

create or replace view public.vw_device_inventory_state
with (security_invoker = true) as
select
  p.id as device_product_id,
  p.external_code,
  p.name,
  p.category,
  p.brand_name,
  p.model,
  p.active,
  count(u.id) filter (where u.status = 'available')::integer as available_qty,
  count(u.id) filter (where u.status = 'sold')::integer as sold_qty,
  count(u.id) filter (where u.status in ('inactive','damaged','lost','retired'))::integer as unavailable_qty,
  count(u.id)::integer as physical_units,
  coalesce(sum(u.cost) filter (where u.status = 'available'), 0)::numeric(14,4) as available_cost_value
from public.device_products p
left join public.device_units u on u.device_product_id = p.id
group by p.id, p.external_code, p.name, p.category, p.brand_name, p.model, p.active;

create or replace view public.vw_device_unit_trace
with (security_invoker = true) as
select
  u.id as device_unit_id,
  p.id as device_product_id,
  p.external_code,
  p.name as product_name,
  p.category,
  p.brand_name,
  p.model,
  u.serial_code,
  u.lot_no,
  u.expires_at,
  u.status,
  u.cost,
  u.source_doc_no,
  u.registered_at,
  ru.display_name as registered_by_name,
  u.sold_at,
  su.display_name as sold_by_name,
  s.sale_no,
  s.expediente,
  u.note
from public.device_units u
join public.device_products p on p.id = u.device_product_id
left join public.app_users ru on ru.id = u.registered_by
left join public.app_users su on su.id = u.sold_by
left join public.device_sales s on s.id = u.sale_id;

insert into public.device_products (
  external_code, name, category, brand_code, brand_name, presentation_name,
  sale_price, default_cost, active, requires_serial, requires_expiration, source_file
) values
  (804, 'Estudio diagnóstico de apnea del sueño', 'Apnea del sueño', 149, null, null, 300, 176.11, true, true, false, 'Listado de Artículos (10).xlsx'),
  (805, 'SIBIONICS GS1 CGM (Monitoreo de Glucosa)', 'Glucosa', 150, null, 'Unidad', 93, 53.10, true, true, true, 'Listado de Articulos (10).xlsx')
on conflict (external_code) do update set
  name = excluded.name,
  category = excluded.category,
  brand_code = excluded.brand_code,
  presentation_name = coalesce(excluded.presentation_name, public.device_products.presentation_name),
  sale_price = excluded.sale_price,
  default_cost = excluded.default_cost,
  active = excluded.active,
  requires_serial = true,
  requires_expiration = excluded.requires_expiration,
  source_file = excluded.source_file,
  source_loaded_at = now();

create or replace function public.rpc_device_product_search(
  p_session_token text,
  p_query text default '',
  p_limit integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_role public.user_role;
  v_q text := lower(trim(coalesce(p_query,'')));
  v_limit integer := greatest(1, least(coalesce(p_limit, 30), 100));
begin
  select role into v_role from public.app_require_session(p_session_token);
  if v_role not in ('admin','dispatch','cashier') then
    raise exception 'No autorizado para consultar dispositivos';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(x) order by x.name)
    from (
      select
        s.device_product_id,
        s.external_code,
        s.name,
        s.category,
        s.brand_name,
        s.model,
        s.active,
        s.available_qty,
        s.sold_qty,
        s.unavailable_qty,
        s.physical_units,
        s.available_cost_value,
        p.sale_price,
        p.default_cost
      from public.vw_device_inventory_state s
      join public.device_products p on p.id = s.device_product_id
      where v_q = ''
         or lower(s.name) like '%' || v_q || '%'
         or lower(coalesce(s.category,'')) like '%' || v_q || '%'
         or lower(coalesce(s.brand_name,'')) like '%' || v_q || '%'
         or lower(coalesce(s.model,'')) like '%' || v_q || '%'
         or s.external_code::text = v_q
      order by s.name
      limit v_limit
    ) x
  ), '[]'::jsonb);
end;
$$;

create or replace function public.rpc_device_unit_register(
  p_session_token text,
  p_external_code integer,
  p_serial_code text,
  p_lot_no text default null,
  p_expires_at date default null,
  p_cost numeric default null,
  p_source_doc_no text default null,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id uuid;
  v_role public.user_role;
  v_product public.device_products%rowtype;
  v_unit_id uuid;
begin
  select user_id, role into v_user_id, v_role from public.app_require_session(p_session_token);
  if v_role <> 'admin' then
    raise exception 'Solo administrador puede registrar unidades de dispositivos';
  end if;

  if length(trim(coalesce(p_serial_code,''))) = 0 then
    raise exception 'Codigo unico requerido';
  end if;

  select * into v_product
  from public.device_products
  where external_code = p_external_code and active = true;

  if v_product.id is null then
    raise exception 'Producto/dispositivo no activo o no existe';
  end if;

  insert into public.device_units(
    device_product_id, serial_code, lot_no, expires_at, cost, source_doc_no,
    registered_by, note
  ) values (
    v_product.id, trim(p_serial_code), nullif(trim(coalesce(p_lot_no,'')), ''),
    p_expires_at, coalesce(p_cost, v_product.default_cost), nullif(trim(coalesce(p_source_doc_no,'')), ''),
    v_user_id, nullif(trim(coalesce(p_note,'')), '')
  )
  returning id into v_unit_id;

  insert into public.device_inventory_movements(
    device_unit_id, device_product_id, serial_code, movement_type, qty_delta,
    source_type, source_id, source_event_key, note, created_by
  ) values (
    v_unit_id, v_product.id, trim(p_serial_code), 'receive', 1,
    'device_unit_register', v_unit_id, 'device_unit_register:' || lower(regexp_replace(trim(p_serial_code), '\s+', '', 'g')),
    'Ingreso de unidad serializada', v_user_id
  )
  on conflict (source_event_key) where source_event_key is not null do nothing;

  return jsonb_build_object('unit_id', v_unit_id, 'status', 'available');
exception
  when unique_violation then
    raise exception 'El codigo unico ya existe: %', p_serial_code;
end;
$$;

create or replace function public.rpc_device_unit_lookup(
  p_session_token text,
  p_serial_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_role public.user_role;
  v_serial text := lower(regexp_replace(trim(coalesce(p_serial_code,'')), '\s+', '', 'g'));
begin
  select role into v_role from public.app_require_session(p_session_token);
  if v_role not in ('admin','dispatch','cashier') then
    raise exception 'No autorizado para consultar dispositivos';
  end if;

  if v_serial = '' then
    return null;
  end if;

  return (
    select to_jsonb(x)
    from (
      select
        u.device_unit_id,
        u.device_product_id,
        u.external_code,
        u.product_name,
        u.category,
        u.brand_name,
        u.model,
        u.serial_code,
        u.lot_no,
        u.expires_at,
        u.status,
        u.cost,
        p.sale_price,
        (u.status = 'available' and p.active = true) as can_dispatch
      from public.vw_device_unit_trace u
      join public.device_products p on p.id = u.device_product_id
      where lower(regexp_replace(trim(u.serial_code), '\s+', '', 'g')) = v_serial
      limit 1
    ) x
  );
end;
$$;

create or replace function public.rpc_device_dispatch_submit(
  p_session_token text,
  p_expediente text,
  p_serials jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id uuid;
  v_role public.user_role;
  v_sale_id uuid;
  v_sale_no bigint;
  v_serials text[];
  v_serial text;
  v_unit public.device_units%rowtype;
  v_product public.device_products%rowtype;
begin
  select user_id, role into v_user_id, v_role from public.app_require_session(p_session_token);
  if v_role <> 'dispatch' then
    raise exception 'Solo despacho puede vender dispositivos';
  end if;

  if length(trim(coalesce(p_expediente,''))) = 0 then
    raise exception 'Expediente requerido';
  end if;

  select array_agg(distinct lower(regexp_replace(trim(value), '\s+', '', 'g')))
  into v_serials
  from jsonb_array_elements_text(coalesce(p_serials, '[]'::jsonb)) as serial_items(value)
  where length(trim(value)) > 0;

  if coalesce(array_length(v_serials, 1), 0) = 0 then
    raise exception 'Agrega al menos un dispositivo';
  end if;

  insert into public.device_sales(expediente, status, created_by)
  values (trim(p_expediente), 'confirmed', v_user_id)
  returning id, sale_no into v_sale_id, v_sale_no;

  foreach v_serial in array v_serials loop
    select * into v_unit
    from public.device_units
    where normalized_serial = v_serial
    for update;

    if v_unit.id is null then
      raise exception 'Codigo unico no registrado: %', v_serial;
    end if;

    if v_unit.status <> 'available' then
      raise exception 'El dispositivo % no esta disponible. Estado actual: %', v_unit.serial_code, v_unit.status;
    end if;

    select * into v_product
    from public.device_products
    where id = v_unit.device_product_id
    for update;

    if v_product.id is null or v_product.active is distinct from true then
      raise exception 'Producto no activo para el dispositivo %', v_unit.serial_code;
    end if;

    update public.device_units
    set status = 'sold',
        sold_at = now(),
        sold_by = v_user_id,
        sale_id = v_sale_id
    where id = v_unit.id;

    insert into public.device_sale_items(
      sale_id, device_unit_id, device_product_id, serial_code, product_name_snapshot, price, cost
    ) values (
      v_sale_id, v_unit.id, v_product.id, v_unit.serial_code, v_product.name, v_product.sale_price, v_unit.cost
    );

    insert into public.device_inventory_movements(
      device_unit_id, device_product_id, serial_code, movement_type, qty_delta,
      source_type, source_id, source_event_key, note, created_by
    ) values (
      v_unit.id, v_product.id, v_unit.serial_code, 'sale', -1,
      'device_sale', v_sale_id, 'device_sale:' || v_sale_id::text || ':' || v_unit.id::text,
      'Venta definitiva de dispositivo', v_user_id
    );
  end loop;

  return jsonb_build_object('sale_id', v_sale_id, 'sale_no', v_sale_no, 'items', array_length(v_serials, 1));
end;
$$;

create or replace function public.rpc_device_inventory_overview(
  p_session_token text,
  p_query text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_role public.user_role;
  v_q text := lower(trim(coalesce(p_query,'')));
begin
  select role into v_role from public.app_require_session(p_session_token);
  if v_role not in ('admin','dispatch','cashier') then
    raise exception 'No autorizado para consultar inventario de dispositivos';
  end if;

  return jsonb_build_object(
    'summary', (
      select jsonb_build_object(
        'products', count(*),
        'available_qty', coalesce(sum(available_qty),0),
        'sold_qty', coalesce(sum(sold_qty),0),
        'unavailable_qty', coalesce(sum(unavailable_qty),0),
        'physical_units', coalesce(sum(physical_units),0),
        'available_cost_value', coalesce(sum(available_cost_value),0)
      )
      from public.vw_device_inventory_state
    ),
    'products', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.name)
      from (
        select *
        from public.vw_device_inventory_state
        where v_q = ''
           or lower(name) like '%' || v_q || '%'
           or lower(coalesce(category,'')) like '%' || v_q || '%'
           or external_code::text = v_q
        order by name
        limit 100
      ) x
    ), '[]'::jsonb),
    'recent_units', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.registered_at desc)
      from (
        select *
        from public.vw_device_unit_trace
        where v_q = ''
           or lower(product_name) like '%' || v_q || '%'
           or lower(serial_code) like '%' || v_q || '%'
           or external_code::text = v_q
        order by registered_at desc
        limit 50
      ) x
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.rpc_device_history(
  p_session_token text,
  p_query text default '',
  p_limit integer default 80
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_role public.user_role;
  v_q text := lower(trim(coalesce(p_query,'')));
  v_limit integer := greatest(1, least(coalesce(p_limit,80), 200));
begin
  select role into v_role from public.app_require_session(p_session_token);
  if v_role not in ('admin','cashier','dispatch') then
    raise exception 'No autorizado para consultar historico de dispositivos';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(x) order by x.created_at desc)
    from (
      select
        m.created_at,
        m.movement_type,
        m.qty_delta,
        m.serial_code,
        p.external_code,
        p.name as product_name,
        p.category,
        s.sale_no,
        s.expediente,
        u.display_name as user_name,
        m.note
      from public.device_inventory_movements m
      join public.device_products p on p.id = m.device_product_id
      left join public.device_sales s on s.id = m.source_id and m.source_type = 'device_sale'
      left join public.app_users u on u.id = m.created_by
      where v_q = ''
         or lower(coalesce(m.serial_code,'')) like '%' || v_q || '%'
         or lower(p.name) like '%' || v_q || '%'
         or p.external_code::text = v_q
         or lower(coalesce(s.expediente,'')) like '%' || v_q || '%'
      order by m.created_at desc
      limit v_limit
    ) x
  ), '[]'::jsonb);
end;
$$;

revoke all on public.vw_device_inventory_state from anon, authenticated;
revoke all on public.vw_device_unit_trace from anon, authenticated;
grant execute on function public.rpc_device_product_search(text, text, integer) to anon, authenticated;
grant execute on function public.rpc_device_unit_register(text, integer, text, text, date, numeric, text, text) to anon, authenticated;
grant execute on function public.rpc_device_unit_lookup(text, text) to anon, authenticated;
grant execute on function public.rpc_device_dispatch_submit(text, text, jsonb) to anon, authenticated;
grant execute on function public.rpc_device_inventory_overview(text, text) to anon, authenticated;
grant execute on function public.rpc_device_history(text, text, integer) to anon, authenticated;
